FROM getmeili/meilisearch:latest

ENV MEILI_HOST=0.0.0.0:7700
ENV MEILI_ENV=production
ENV MEILI_MASTER_KEY=wave-meili-master-key-2026
ENV MEILI_NO_ANALYTICS=true
ENV MEILI_MAX_INDEXING_THREADS=2

EXPOSE 7700

CMD ["meilisearch"]
